export const dataForCharts = [
	{
		productName: 'Big Dipper Arc Brass Floor Lamp',
		productType: 'Lamps',
		price: 549,
		month: 1,
		date: '2023-01-06',
		quantity: 1,
	},
	{
		productName: 'Bay Antique Brass Circle Wall Shelf',
		productType: 'Wall Deco',
		price: 299,
		month: 1,
		date: '2023-01-08',
		quantity: 1,
	},
	{
		productName: 'Tablon Snow Sofa',
		productType: 'Sofas',
		price: 2999,
		month: 1,
		date: '2023-01-09',
		quantity: 1,
	},
	{
		productName: 'Slope Cement Coffee Table',
		productType: 'Tables',
		price: 824,
		month: 1,
		date: '2023-01-26',
		quantity: 1,
	},
	{
		productName: 'Big Dipper Arc Brass Floor Lamp',
		productType: 'Lamps',
		price: 1098,
		month: 1,
		date: '2023-01-06',
		quantity: 2,
	},
	{
		productName: 'Tall White Ceramic Table Lamp With Jute Shade',
		productType: 'Lamps',
		price: 599,
		month: 1,
		date: '2023-01-05',
		quantity: 1,
	},
	{
		productName: 'Prix Leather And Polished Brass Floor Lamp',
		productType: 'Lamps',
		price: 2547,
		month: 1,
		date: '2023-01-12',
		quantity: 3,
	},
	{
		productName: 'Wilde Blacken Brass Task Table',
		productType: 'Lamps',
		price: 549,
		month: 2,
		date: '2023-02-26',
		quantity: 1,
	},
	{
		productName: 'Hide N Seek Large Acacia Storage Shelf',
		productType: 'Wall Deco',
		price: 700,
		month: 2,
		date: '2023-02-26',
		quantity: 2,
	},
	{
		productName: 'Trio Gold Floor Lamp',
		productType: 'Lamps',
		price: 449,
		month: 2,
		date: '2023-02-06',
		quantity: 1,
	},
	{
		productName: 'Andes Sofa',
		productType: 'Sofas',
		price: 1679,
		month: 2,
		date: '2023-02-26',
		quantity: 1,
	},
	{
		productName: 'Pilla Wood Tiered Coffee Table',
		productType: 'Tables',
		price: 1199,
		month: 2,
		date: '2023-02-16',
		quantity: 1,
	},
	{
		productName: 'Savile Leather Tufted Sofa',
		productType: 'Sofas',
		price: 7199,
		month: 2,
		date: '2023-02-05',
		quantity: 1,
	},
	{
		productName: 'Spin Rotating Coffee Table',
		productType: 'Tables',
		price: 1299,
		month: 2,
		date: '2023-02-13',
		quantity: 1,
	},
	{
		productName: 'Limestone Table Lamp',
		productType: 'Lamps',
		price: 750,
		month: 2,
		date: '2023-02-28',
		quantity: 1,
	},
	{
		productName: 'Limestone Table Lamp',
		productType: 'Lamps',
		price: 1500,
		month: 3,
		date: '2023-03-08',
		quantity: 2,
	},
	{
		productName: 'Blaine Polished Brass Wall Shelf',
		productType: 'Wall Deco',
		price: 269,
		month: 3,
		date: '2023-03-28',
		quantity: 1,
	},
	{
		productName: 'Matra Camel Velvet Sofa',
		productType: 'Sofas',
		price: 3999,
		month: 3,
		date: '2023-03-16',
		quantity: 1,
	},
	{
		productName: 'Carve Travertine Table',
		productType: 'Tables',
		price: 599,
		month: 3,
		date: '2023-03-14',
		quantity: 1,
	},
	{
		productName: 'Carve Travertine Table',
		productType: 'Tables',
		price: 1198,
		month: 3,
		date: '2023-03-18',
		quantity: 2,
	},
	{
		productName: 'Slope Cement Coffee Table',
		productType: 'Tables',
		price: 824,
		month: 3,
		date: '2023-03-14',
		quantity: 1,
	},

	{
		productName: 'Kendo Polished Brass Table Lamp',
		productType: 'Lamps',
		price: 1056,
		month: 4,
		date: '2023-04-09',
		quantity: 4,
	},
	{
		productName: 'Blaine Polished Brass Wall Shelf',
		productType: 'Wall Deco',
		price: 807,
		month: 4,
		date: '2023-04-08',
		quantity: 3,
	},
	{
		productName: 'Marconi Tufted Rust Velvet Sofa',
		productType: 'Sofas',
		price: 4899,
		month: 4,
		date: '2023-04-24',
		quantity: 1,
	},
	{
		productName: 'Hide N Seek Large Acacia Storage Shelf',
		productType: 'Wall Deco',
		price: 349,
		month: 4,
		date: '2023-04-18',
		quantity: 1,
	},
	{
		productName: 'Andes Sofa',
		productType: 'Sofas',
		price: 1679,
		month: 4,
		date: '2023-04-24',
		quantity: 1,
	},
	{
		productName: 'Matter Grey Cement Coffee Table',
		productType: 'Tables',
		price: 1399,
		month: 4,
		date: '2023-04-12',
		quantity: 1,
	},

	{
		productName: 'Limestone Table Lamp',
		productType: 'Lamps',
		price: 750,
		month: 5,
		date: '2023-05-04',
		quantity: 1,
	},
	{
		productName: 'Bay Antique Brass Circle Wall Shelf',
		productType: 'Wall Deco',
		price: 299,
		month: 5,
		date: '2023-05-24',
		quantity: 1,
	},
	{
		productName: 'Marconi Tufted Rust Velvet Sofa',
		productType: 'Sofas',
		price: 4899,
		month: 5,
		date: '2023-05-14',
		quantity: 1,
	},
	{
		productName: 'Matra Camel Velvet Sofa',
		productType: 'Sofas',
		price: 3999,
		month: 5,
		date: '2023-05-16',
		quantity: 1,
	},

	{
		productName: 'Carve Travertine Table',
		productType: 'Tables',
		price: 1797,
		month: 5,
		date: '2023-05-29',
		quantity: 3,
	},
	{
		productName: 'Slope Cement Coffee Table',
		productType: 'Tables',
		price: 824,
		month: 5,
		date: '2023-05-14',
		quantity: 1,
	},
	{
		productName: 'Prix Leather And Polished Brass Floor Lamp',
		productType: 'Lamps',
		price: 849,
		month: 5,
		date: '2023-05-29',
		quantity: 1,
	},
	{
		productName: 'Limestone Table Lamp',
		productType: 'Lamps',
		price: 1500,
		month: 5,
		date: '2023-05-19',
		quantity: 2,
	},
	{
		productName: 'Big Dipper Arc Brass Floor Lamp',
		productType: 'Lamps',
		price: 1098,
		month: 6,
		date: '2023-06-06',
		quantity: 2,
	},
	{
		productName: 'Bay Antique Brass Circle Wall Shelf',
		productType: 'Wall Deco',
		price: 1495,
		month: 6,
		date: '2023-06-24',
		quantity: 5,
	},
	{
		productName: 'Marconi Tufted Rust Velvet Sofa',
		productType: 'Sofas',
		price: 9798,
		month: 6,
		date: '2023-06-14',
		quantity: 2,
	},

	{
		productName: 'Carve Travertine Table',
		productType: 'Tables',
		price: 599,
		month: 6,
		date: '2023-06-29',
		quantity: 1,
	},
	{
		productName: 'Limestone Table Lamp',
		productType: 'Lamps',
		price: 750,
		month: 6,
		date: '2023-06-12',
		quantity: 1,
	},
	{
		productName: 'Tall White Ceramic Table Lamp With Jute Shade',
		productType: 'Lamps',
		price: 599,
		month: 6,
		date: '2023-06-29',
		quantity: 1,
	},
	{
		productName: 'Camden Sofa ',
		productType: 'Sofas',
		price: 3699,
		month: 6,
		date: '2023-06-19',
		quantity: 1,
	},
];
